name = "ATM10 To the Sky"
author = "ATMTeam"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5b2cd519a5dfcbb487801854d74f16cb28d4c31e64627759b1c275d6526efe9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
